// Generates src/content.generated.ts from the .md files in /content.
// Run automatically by `npm run dev` / `npm run build` (see package.json).
// Edit the .md files, not the generated output.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { marked } from "marked";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CONTENT_DIR = path.resolve(__dirname, "../content");
const OUT_FILE = path.resolve(__dirname, "../src/content.generated.ts");

marked.use({
  renderer: {
    link({ href, title, tokens }) {
      const text = this.parser.parseInline(tokens);
      const external = /^https?:\/\//.test(href);
      const attrs = external ? ' target="_blank" rel="noreferrer"' : "";
      const titleAttr = title ? ` title="${title}"` : "";
      return `<a href="${href}"${titleAttr}${attrs}>${text}</a>`;
    },
  },
});

function readMd(name) {
  const raw = fs.readFileSync(path.join(CONTENT_DIR, `${name}.md`), "utf-8");
  const { data, content } = matter(raw);
  return { data, html: marked.parse(content.trim()).trim() };
}

const site = readMd("site").data;

const about = readMd("about");
const publications = readMd("about-publications");
const people = [
  "about-people-roger-brent",
  "about-people-oleg-serikov",
  "about-people-dmitrii-volkov",
].map((name) => {
  const { data, html } = readMd(name);
  return { name: data.name, role: data.role, bioHtml: html };
});

const technology = readMd("technology");
const technologyTodo = readMd("technology-todo");

const research = readMd("research");
const researchTodo = readMd("research-todo");

const output = `// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Edit the .md files in /content instead; this file regenerates on
// \`npm run dev\` / \`npm run build\` (or manually via \`npm run content\`).

export interface Person {
  name: string;
  role: string;
  bioHtml: string;
}

export const SITE = ${JSON.stringify(site, null, 2)} as const;

export const ABOUT = {
  heroTitle: ${JSON.stringify(about.data.hero_title)} as [string, string],
  pullQuote: ${JSON.stringify(about.data.pull_quote)},
  peopleHeading: ${JSON.stringify(about.data.people_heading)},
  publicationsHeading: ${JSON.stringify(about.data.publications_heading)},
  documentHubLabel: ${JSON.stringify(about.data.document_hub_label)},
  missionHtml: ${JSON.stringify(about.html)},
  publicationsHtml: ${JSON.stringify(publications.html)},
} as const;

export const PEOPLE: Person[] = ${JSON.stringify(people, null, 2)};

export const TECHNOLOGY = {
  heroTitle: ${JSON.stringify(technology.data.hero_title)} as [string, string],
  subheading: ${JSON.stringify(technology.data.subheading)},
  bodyHtml: ${JSON.stringify(technology.html)},
  todoHtml: ${JSON.stringify(technologyTodo.html)},
} as const;

export const RESEARCH = {
  heroTitle: ${JSON.stringify(research.data.hero_title)} as [string, string],
  subheading: ${JSON.stringify(research.data.subheading)},
  bodyHtml: ${JSON.stringify(research.html)},
  todoHtml: ${JSON.stringify(researchTodo.html)},
} as const;
`;

fs.writeFileSync(OUT_FILE, output);
console.log(`Generated ${path.relative(process.cwd(), OUT_FILE)} from ${CONTENT_DIR}`);
